openapi: 3.0.3
info:
  version: '1.0'
  title: "CDM CombinedSearch Service"
  description: "Set of services related to CDM combined search operations"
  termsOfService: ""
  contact:
    email: "CDM_Dev_Team_&_EWs@mckinsey.com"
tags:
  - name: "CDM CombinedSearch Service"
    description: "CDM CombinedSearch Service APIs"
paths:
  /cdmcombinedsearch/cdmCapiqSolr:
    get:
      tags:
        - CDM CombinedSearch Service
      summary: Fetch CDM Capiq Solr records
      description: Retrieve CDM capiq solr client record by party name or party number or capiqid or capiquid
      operationId: cdmCapiqSolr
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
          description: 'Party name present in CDM'
        - name: party_number
          in: query
          required: true
          schema:
            type: number
          description: 'Party Number present in CDM'
        - name: capiq_id
          in: query
          required: true
          schema:
            type: number
          description: 'Capiq Id present in CDM'
        - name: capiq_uid
          in: query
          required: true
          schema:
            type: string
          description: 'Capid Uid present in CDM'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CDMCapiqSolr'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Failure
  /cdmcombinedsearch/v3/companies:
    get:
      tags:
        - CDM CombinedSearch Service
      summary: Fetch CDM , CDM Capiq and Capiq records
      description: Retrieve CDM , CDM Capiq and Capiq records by name or party number or capiqid or capiquid with filter on city or industry or country
      operationId: v3companiesCombinedSearch
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string
          description: 'Party name present in CDM'
        - name: party_number
          in: query
          required: false
          schema:
            type: number
          description: 'Party Number present in CDM'
        - name: capiq_id
          in: query
          required: false
          schema:
            type: number
          description: 'Capiq Id present in CDM'
        - name: capiq_uid
          in: query
          required: false
          schema:
            type: string
          description: 'Capid Uid present in CDM'
        - name: country
          in: query
          required: false
          schema:
            type: string
          description: 'Country present in CDM'
        - name: sector
          in: query
          required: false
          schema:
            type: string
          description: 'Sector present in CDM'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CombinedSearchResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Failure

components:
  schemas:
    CDMCapiqSolr:
      title: CDMCapiqSolr
      type: object
      properties:
        Response:
          $ref: '#/components/schemas/CDMCapiqSolrResponse'
      required:
        - CDMCapiqSolrResponse
    CDMCapiqSolrResponse:
      title: CDMCapiqSolrResponse
      type: object
      properties:
        NumFound:
          description: ''
          type: integer
          format: int32
        Docs:
          $ref: '#/components/schemas/CDMCapiqSolrDoc'
      required:
        - NumFound
        - Docs
    CDMCapiqSolrDoc:
      title: CDMCapiqSolrDoc
      type: object
      properties:
        Id:
          description: ''
          type: integer
          format: int32
        PartyId:
          description: ''
          type: integer
          format: int32
        PartyNumber:
          description: ''
          type: integer
          format: int32
        AnticipatedMasterClientNumber:
          description: ''
          type: integer
          format: int32
        CapiqId:
          description: ''
          type: integer
          format: int32
        CapiqUid:
          description: ''
          type: integer
          format: int32
        Source:
          description: ''
          type: string
        PartyNumberStr:
          description: ''
          type: string
        TrimmedPartyName:
          description: ''
          type: string
        PartyName:
          description: ''
          type: string
        PartyNameTxt:
          description: ''
          type: string
        ExactPartyName:
          description: ''
          type: string
        AddressLine1:
          description: ''
          type: string
        AddressLine2:
          description: ''
          type: string
        PostalCode:
          description: ''
          type: string
        City:
          description: ''
          type: string
        StateProvince:
          description: ''
          type: string
        CountryCode:
          description: ''
          type: string
        CountryName:
          description: ''
          type: string
        CapiqIdStr:
          description: ''
          type: string
        CapiqName:
          description: ''
          type: string
        CapiqNameTxt:
          description: ''
          type: string
        CapiqCity:
          description: ''
          type: string
        CapiqState:
          description: ''
          type: string
        CapiqCountry:
          description: ''
          type: string
        CapiqIndustry:
          description: ''
          type: string
        capiqRevenue:
          description: ''
          type: integer
          format: int32
        ComStatus:
          description: ''
          type: string
        ultimate_capiq_parent_party_number:
          description: ''
          type: integer
          format: int32
        ultimate_capiq_parent_party_name:
          description: ''
          type: string
        taxonomy_sector1:
          description: ''
          type: string
        taxonomy_sector2:
          description: ''
          type: string
        taxonomy_sector3:
          description: ''
          type: string
        taxonomy_sector4:
          description: ''
          type: string
        taxonomy_industry1:
          description: ''
          type: string
        taxonomy_industry2:
          description: ''
          type: string
        taxonomy_industry3:
          description: ''
          type: string
        taxonomy_industry4:
          description: ''
          type: string
        taxonomy_industry_segment1:
          description: ''
          type: string
        taxonomy_industry_segment2:
          description: ''
          type: string
        taxonomy_industry_segment3:
          description: ''
          type: string
        taxonomy_industry_segment4:
          description: ''
          type: string
        taxonomy_industry_subsegment1:
          description: ''
          type: string
        taxonomy_industry_subsegment2:
          description: ''
          type: string
        taxonomy_industry_subsegment3:
          description: ''
          type: string
        taxonomy_industry_subsegment4:
          description: ''
          type: string
        taxonomy_type1:
          description: ''
          type: string
        taxonomy_type2:
          description: ''
          type: string
        taxonomy_type3:
          description: ''
          type: string
        taxonomy_type4:
          description: ''
          type: string
        taxonomy_priority_tag1:
          description: ''
          type: string
        taxonomy_priority_tag2:
          description: ''
          type: string
        taxonomy_priority_tag3:
          description: ''
          type: string
        taxonomy_priority_tag4:
          description: ''
          type: string
        taxonomy_priority_tag1_id:
          description: ''
          type: integer
          format: int32
        taxonomy_priority_tag2_id:
          description: ''
          type: integer
          format: int32
        taxonomy_priority_tag3_id:
          description: ''
          type: integer
          format: int32
        taxonomy_priority_tag4_id:
          description: ''
          type: integer
          format: int32

    Object:
      type: "object"
      properties: { }
    Address:
      type: "object"
      properties:
        line1:
          $ref: "#/components/schemas/Object"
        line2:
          $ref: "#/components/schemas/Object"
        line3:
          $ref: "#/components/schemas/Object"
        line4:
          $ref: "#/components/schemas/Object"
        province:
          $ref: "#/components/schemas/Object"
        city:
          $ref: "#/components/schemas/Object"
        state:
          $ref: "#/components/schemas/Object"
        postalCode:
          $ref: "#/components/schemas/Object"
        country:
          $ref: "#/components/schemas/Object"
        countryCode:
          $ref: "#/components/schemas/Object"
        county:
          $ref: "#/components/schemas/Object"
    CombinedSearchItem:
      type: "object"
      properties:
        source:
          type: "string"
        partyId:
          $ref: "#/components/schemas/Object"
        partyNumber:
          $ref: "#/components/schemas/Object"
        organizationName:
          $ref: "#/components/schemas/Object"
        practiceIndustry:
          $ref: "#/components/schemas/Object"
        capiqId:
          $ref: "#/components/schemas/Object"
        capiqIdStr:
          type: "string"
        capiqUid:
          $ref: "#/components/schemas/Object"
        capiqName:
          type: "string"
        capiqRevenue:
          type: "integer"
          format: "int64"
        parentPartyId:
          type: "integer"
          format: "int64"
        parentPartyNumber:
          type: "integer"
          format: "int64"
        parentPartyName:
          type: "string"
        anticipatedMasterClientNumber:
          $ref: "#/components/schemas/Object"
        duplicateName:
          type: "boolean"
        ultimate_capiq_parent_party_number:
          $ref: "#/components/schemas/Object"
        ultimate_capiq_parent_party_name:
          description: ''
          type: string
        taxonomy_sector1:
          description: ''
          type: string
        taxonomy_sector2:
          description: ''
          type: string
        taxonomy_sector3:
          description: ''
          type: string
        taxonomy_sector4:
          description: ''
          type: string
        taxonomy_industry1:
          description: ''
          type: string
        taxonomy_industry2:
          description: ''
          type: string
        taxonomy_industry3:
          description: ''
          type: string
        taxonomy_industry4:
          description: ''
          type: string
        taxonomy_industry_segment1:
          description: ''
          type: string
        taxonomy_industry_segment2:
          description: ''
          type: string
        taxonomy_industry_segment3:
          description: ''
          type: string
        taxonomy_industry_segment4:
          description: ''
          type: string
        taxonomy_industry_subsegment1:
          description: ''
          type: string
        taxonomy_industry_subsegment2:
          description: ''
          type: string
        taxonomy_industry_subsegment3:
          description: ''
          type: string
        taxonomy_industry_subsegment4:
          description: ''
          type: string
        taxonomy_type1:
          description: ''
          type: string
        taxonomy_type2:
          description: ''
          type: string
        taxonomy_type3:
          description: ''
          type: string
        taxonomy_type4:
          description: ''
          type: string
        taxonomy_priority_tag1:
          description: ''
          type: string
        taxonomy_priority_tag2:
          description: ''
          type: string
        taxonomy_priority_tag3:
          description: ''
          type: string
        taxonomy_priority_tag4:
          description: ''
          type: string
        taxonomy_priority_tag1_id:
          $ref: "#/components/schemas/Object"
        taxonomy_priority_tag2_id:
          $ref: "#/components/schemas/Object"
        taxonomy_priority_tag3_id:
          $ref: "#/components/schemas/Object"
        taxonomy_priority_tag4_id:
          $ref: "#/components/schemas/Object"
        address:
          $ref: "#/components/schemas/Address"
    CombinedSearchResponse:
      type: "object"
      properties:
        count:
          type: "integer"
          format: "int32"
        items:
          type: "array"
          items:
            $ref: "#/components/schemas/CombinedSearchItem"