openapi: 3.0.3
info:
  title: "GOC Offices API"
  version: "2.0"
  description: This is the GOC Offices API

servers:
  - url: https://dev-api.mckinsey.com/

externalDocs:
  description: Find out more
  url: https://apidocs.intranet.mckinsey.com

tags:
  - name: GocOfficesV2
    externalDocs:
      description: Find out more
      url: 'https://dev-apiportal.mckinsey.com/apis'

paths:
  /firm-reference-data/v2/goc_offices:
    get:
      tags:
        - GocOfficesV2
      operationId: getGocOffices
      summary: This fetches the details for goc offices (DataHub)
      description: |-
        <b>API Description:</b> This API provides goc offices given the search query (q). The source is pick list
        of goc offices  i.e offices  where the Firm members is accounted for from a financial/accounting perspective.<br/>
        <b>Business Logic/Filter on data :</b>All data available from datahub is exposed on this API. Consumer needs
        to provide parameters and input as per requirement eg if you need only active goc offices then
        use activeInactiveFlag and if you need offices created in a specific range then pass accordingly<br/>
        <b>Sourced from:</b> NA<br/>
        <b>Source overview:</b> APIx>Solr>DataHub<br/>
        <b>Works with "Try it Out"?:</b> Yes<br/>
        <b>Application Context/User Context/Both :</b>Application Context<br/>
        <b>Data refresh frequency:</b> Every 30 minutes starting at 5th minute of the hour<br/>
        <b>Caching and frequency:</b> None<br/>
        <b>Any exceptional scenarios associated to API?:</b> None<br/>
      parameters:
      - name: q
        in: query
        description: Search term
        required: true
        schema:
          type: string
      - name: gocOfficeCode
        in: query
        description: Three letter code which identifies the Goc Office code to which Firm Member belongs to.
        schema:
          type: string
      - name: gocOfficeDesc
        in: query
        description: The description of the Goc Office.
        schema:
          type: string
      - name: gocOfficeClusterCode
        in: query
        description: Two letter code to which a Goc office is rolled up.
        schema:
          type: string
      - name: gocOfficeClusterDesc
        in: query
        description: The description of the cluster to which office is rolled up.
        schema:
          type: string
      - name: gocOfficeType
        in: query
        description: 'Indicates the type of GOC office: eg: Practice, RTS, Firm.. Etc.'
        schema:
          type: string
      - name: officeFromDate
        in: query
        description: 'The date on which a office value becomes available for use. The input format is date. Ex: 1900-01-01T00:00:00Z'
        schema:
          type: string
      - name: officeToDate
        in: query
        description: |-
          The date on which a office value becomes invalid and is no longer available for use in creating transactions.
          The input format is date.
          Ex: 1900-01-01T00:00:00Z
        schema:
          type: string
      - name: clusterFromDate
        in: query
        description: |-
          The date on which a cluster value becomes available for use.
          The input format is date.
          Ex: 1900-01-01T00:00:00Z'
        schema:
          type: string
      - name: clusterToDate
        in: query
        description: |-
          The date on which a cluster value becomes invalid and is no longer available for use in creating transactions.
          The input format is date.
          Ex: 1900-01-01T00:00:00Z
        schema:
          type: string
      - name: orgId
        in: query
        description: Unique (numeric) identifier for a responsibility organization.
        schema:
          type: string
      - name: orgName
        in: query
        description: Name for a responsibility organization
        schema:
          type: string
      - name: respOrg
        in: query
        description: Indicates the 3-letter location code prefix for a set of books responsibility.
        schema:
          type: string
      - name: es1RespOrg
        in: query
        description: TBD
        schema:
          type: string
      - name: mgmtSobCountryCode
        in: query
        description: TBD
        schema:
          type: string
      - name: isoCountryCode
        in: query
        description: TBD
        schema:
          type: string
      - name: activeInactiveFlag
        in: query
        description: |-
          Indicates whether GOC office is Active or Inactive.
          Example:
            Active - would give all active records
            Inactive - would give records that have been end dated (as in the source) and legacy records (records the way
                    it used to be in ORS or other sources and the value might not be as per new datahub design).
          Passing no value would give all records.'
        schema:
          type: string
      - name: fields
        in: query
        description: Fields to be fetched in response
        explode: false
        style: form
        schema:
          type: array
          items:
            type: string
      - name: offset
        in: query
        description: Start of record
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        description: No of records to be fetched
        schema:
          type: integer
          format: int32
      - name: sort
        in: query
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetGocOfficesResponse'
          description: Success
        "403":
          description: Forbidden
        "404":
          description: Resource not found
        "500":
          description: Internal Server Error
      security:
      - oauth_clientcredentials: []

  /firm-reference-data/v2/goc_offices/autosuggest:
    get:
      tags:
        - GocOfficesV2
      operationId: gocOfficesV2Autosuggest
      summary: This fetches the autosuggest details for goc offices(DataHub)
      description: |-
        <b>API Description :</b> This API autosuggest goc offices given the search query (q).
        The source is pick list of goc offices  i.e offices  where the Firm members is accounted
        for from a financial/accounting perspective.<br>
        <b>Business Logic/Filter on data :</b> All data available from datahub is exposed on this API. Consumer needs
        to provide parameters and input as per requirement eg if you need only active goc offices then
        use activeInactiveFlag and if you need offices created in a specific range then pass accordingly<br/>
        <b>Sourced from:</b> NA<br/>
        <b>Source overview : </b> APIx>Solr>DataHub<br/>
        <b>Works with "Try it Out"?:</b> Yes<br/>
        <b>Application Context/User Context/Both:</b> Application Context<br/>
        <b>Data refresh frequency :</b> Every 30 minutes starting at 5th minute of the hour<br/>
        <b>Caching and frequency :</b> None<br/><b>Any
        exceptional scenarios associated to API?:</b> None <br/>
      parameters:
        - name: q
          in: query
          description: Search term
          required: true
          schema:
            type: string
        - name: gocOfficeCode
          in: query
          description: Three letter code which identifies the Goc Office code to which Firm Member belongs to.
          schema:
            type: string
        - name: gocOfficeDesc
          in: query
          description: The description of the Goc Office.
          schema:
            type: string
        - name: gocOfficeClusterCode
          in: query
          description: Two letter code to which a Goc office is rolled up.
          schema:
            type: string
        - name: gocOfficeClusterDesc
          in: query
          description: The description of the cluster to which office is rolled up.
          schema:
            type: string
        - name: gocOfficeType
          in: query
          description: 'Indicates the type of GOC office: eg: Practice, RTS, Firm... Etc.'
          schema:
            type: string
        - name: officeFromDate
          in: query
          description: |-
            The date on which a office value becomes available for use.
            The input format is date.
            Ex: 1900-01-01T00:00:00Z
          schema:
            type: string
        - name: officeToDate
          in: query
          description: |-
            The date on which a office value becomes invalid and is no longer available for use in creating transactions.
            The input format is date.
            Ex: 1900-01-01T00:00:00Z
          schema:
            type: string
        - name: clusterFromDate
          in: query
          description: 'The date on which a cluster value becomes available for use. The input format is date. Ex: 1900-01-01T00:00:00Z'
          schema:
            type: string
        - name: clusterToDate
          in: query
          description: |-
            The date on which a cluster value becomes invalid and is no longer available for use in creating transactions.
            The input format is date.
            Ex: 1900-01-01T00:00:00Z
          schema:
            type: string
        - name: orgId
          in: query
          description: Unique (numeric) identifier for a responsibility organization.
          schema:
            type: string
        - name: orgName
          in: query
          description: Name for a responsibility organization
          schema:
            type: string
        - name: respOrg
          in: query
          description: Indicates the 3-letter location code prefix for a set of books responsibility.
          schema:
            type: string
        - name: es1RespOrg
          in: query
          description: TBD
          schema:
            type: string
        - name: mgmtSobCountryCode
          in: query
          description: TBD
          schema:
            type: string
        - name: isoCountryCode
          in: query
          description: TBD
          schema:
            type: string
        - name: activeInactiveFlag
          in: query
          description: |-
            Indicates whether GOC office is Active or Inactive.
            Example:
              Active - would give all active records
              Inactive - would give records that have been end dated (as in the source) and legacy records (records the way
                    it used to be in ORS or other sources and the value might not be as per new datahub design).
            Passing no value would give all records.
          schema:
            type: string
        - name: fields
          in: query
          description: Fields to be fetched in response
          explode: false
          style: form
          schema:
            type: array
            items:
              type: string
        - name: offset
          in: query
          description: Start of record
          schema:
            type: integer
            format: int32
        - name: limit
          in: query
          description: No of records to be fetched
          schema:
            type: integer
            format: int32
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetGocOfficesAutosuggestResponse'
          description: Success
        "403":
          content: {}
          description: Forbidden
        "404":
          description: Resource not found
        "500":
          description: Internal Server Error
      security:
        - oauth_clientcredentials: []

components:
  schemas:
    GetGocOfficesResponse:
      type: object
      properties:
        response:
          $ref: '#/components/schemas/GetGocOfficesPayload'
        facet_counts:
          $ref: '#/components/schemas/FacetCounts'

    GetGocOfficesAutosuggestResponse:
      type: object
      properties:
        response:
          $ref: '#/components/schemas/GetGocOfficesPayload'

    GetGocOfficesPayload:
      type: object
      properties:
        noOfRecords:
          description: total Number of Records fetched
          type: integer
          format: int64
        apiVersion:
          type: string
        params:
          $ref: '#/components/schemas/Parameters'
        gocOffices:
          type: array
          items:
            $ref: '#/components/schemas/GocOffice'

    Parameters:
      description: optional query parameters
      type: object
      properties:
        q:
          description: |-
            Use the "q" parameter to search for the goc offices. For functions for a specific person fmno use q=fmno:127642.
            For all records for a specific function use q=function:"Operations" or you could also use a wildcard,
            e.g.: q=function:"Strategy%".
            For multiple fields separate the fields by AND, e.g.: q=fmno:127642 AND function:"Operations"
          type: string
        limit:
          description: |-
            Indicates no of records to be returned.
            Default is 10.
            Use this in combination with offset for paginating results
          type: integer
          format: int32
        offset:
          description: |-
            Indicates start of record.
            Start of record by default is from 1.
            Use this in combination with limit for paginating results
          type: integer
          format: int32

    GocOffice:
      description: Details for GOC Offices Autosuggest
      type: object
      properties:
        gocOfficeDesc:
          description: The description of the Goc Office
          type: string
        updateDate:
          description: Audit column which identifies the date when the Goc office was last updated in the Data Hub
          type: string
        officeFromDate:
          description: The date on which a office value becomes available for use.
          type: string
        gocOfficeClusterCode:
          description: Two letter code to which a Goc office is rolled up
          type: string
        createDate:
          description: Audit column which identifies the date when the Goc office was created in the Data Hub
          type: string
        clusterFromDate:
          description: The date on which a cluster value becomes available for use.
          type: string
        gocOfficeClusterId:
          description: |-
            A foreign key referring to the primary key of the Cluster_Ref Table. Identifies the 2 letter cluster code
            sourced from ebs finance that the Goc Office belongs to
          type: integer
          format: int64
        gocOfficeId:
          description: Unqiue identifier for a record identified by a unique goc office code
          type: integer
          format: int64
        gocOfficeClusterDesc:
          description: The description of the cluster to which office is rolled up
          type: string
        gocOfficeCode:
          description: Three letter code which identifies the Goc Office code to which Firm Member belongs to
          type: string
        gocOfficeType:
          description: 'Indicates the type of GOC office: eg: Practice, RTS, Firm... Etc.'
          type: string
        officeToDate:
          description: |-
            The date on which a office value becomes invalid and is no longer available for use in creating transactions.
          type: string
        clusterToDate:
          description: |-
            The date on which a cluster value becomes invalid and is no longer available for use in creating transactions.
          type: string
        activeInactiveFlag:
          description: |-
            Indicates whether GOC office is Active or Inactive.
            Example:
              Active - would give all active records
              Inactive - would give records that have been end dated (as in the source) and legacy records (records
                the way it used to be in ORS or other sources and the value might not be as per new datahub design).
            Passing no value would give all records.
          type: string
        es1RespOrg:
          description: es1 Resp Org
          type: string
        lastUpdateDate:
          description: Last updated date
          type: string
        mgmtSobCountryCode:
          description: Management Sob Country Code
          type: string
        orgId:
          description: Organization ID
          type: string
        currencyName:
          description: Currency Name
          type: string
        respOrg:
          description: Resp Org
          type: string
        orgName:
          description: Organization Name
          type: string
        isoCountryCode:
          description: ISO Country Code
          type: string
        billingOfficeFlag:
          description: Billing Office Flag
          type: string
        payrollOfficeCode:
          description: Payroll Office Code
          type: string
        currencyCode:
          description: Currency Code
          type: string

    FacetCounts:
      description: List of Facets for the query search
      type: object
      properties:
        facet_queries:
          type: object
        facet_fields:
          $ref: '#/components/schemas/FacetFields'
        facet_ranges:
          type: object
        facet_intervals:
          type: object
        facet_heatmaps:
          type: object

    FacetFields:
      type: object
      properties:
        gocOfficeType:
          type: object
          additionalProperties:
            type: integer
            format: int64
        gocOfficeClusterDesc:
          type: object
          additionalProperties:
            type: integer
            format: int64

  securitySchemes:
    oauth_clientcredentials:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://dev-apioauth.mckinsey.com/asg/oauth2/access_token
          scopes: {}
          tokenUrl: https://dev-apioauth.mckinsey.com/asg/oauth2/access_token?grant_type=client_credentials