openapi: 3.0.3
info:
  title: "Person Skills API"
  version: "1.0"
  description: This is the Person Skills API

servers:
  - url: https://dev-api.mckinsey.com/

externalDocs:
  description: Find out more
  url: https://apidocs.intranet.mckinsey.com

tags:
  - name: PersonSkillsV1
    externalDocs:
      description: Find out more
      url: 'https://dev-apiportal.mckinsey.com/apis'

paths:
  /human-resources-restricted/v1/person_skills:
    get:
      tags:
        - PersonSkillsV1
      operationId: getPersonskills
      summary: The API returns Person Skills
      description: |-
        <b>API Description:</b> This API provides Firm members’ skills as obtained from the Got Skills survey.<br/>
        <b>Business Logic/Filter on data:</b> For the specific set of fields, please use the fields parameter with an asterix or the specific field names. All of the fields in the response are indexed and can be used to filter results.<br/>
        <b>Source overview: </b> APIx>Solr>Datahub<br/>
        <b>Hypermedia Links:</b> No<br/>
        <b>Security Level:</b> Level 2 (Permissioned)<br/>
        <b>Works with "Try it Out"?:</b> Yes<br/>
        <b>Application Context/User Context/Both:</b> Application Context<br/>
        <b>Data refresh frequency :</b>Every 3 hours<br/>
        <b>Caching enabled and time to live:</b> None<br/>
        <b>Any exceptional scenarios associated to API?:</b> The api accepts the access token/apikey only in the header.
        The total no of records displayed are 10 with start record at 1. If you wish to change this, utilize the limit
        and the offset params.<br/>
      parameters:
      - name: q
        in: query
        description: Use the 'q' parameter to do a full text search on Person Skills API.<br/>
        required: true
        schema:
          type: string
      - name: fmno
        in: query
        description: Firm member's/External Worker's Firm  unique identifier of the leadership position
        schema:
          type: string
      - name: skillType
        in: query
        description: The nature of skill, such as technical versus non-technical.The second level of the Skill->>Skill Category->> Skill Type->>Skill Group hierarchy
        schema:
          type: string
      - name: source
        in: query
        description: Origination of data
        schema:
          type: string
      - name: skillCategory
        in: query
        description: The set of the skill.The third level of the Skill->>Skill Category->> Skill Type->>Skill Group hierarchy
        schema:
          type: string
      - name: proficiency
        in: query
        description: The degree of competence of the skill (self reported)
        schema:
          type: string
      - name: skillGroup
        in: query
        description: The first level of the Skill->>Skill Category->> Skill Type->>Skill Group hierarchy
        schema:
          type: string
      - name: skill
        in: query
        description: The particular ability, typically technical ability.The fourth level of the Skill->>Skill Category->> Skill Type->>Skill Group hierarchy
        schema:
          type: string
      - name: surveyQuestionType
        in: query
        description: This field indicates whether the input is User Defined or not, it has two possible values “User Defined” or “Guild Defined”.
        schema:
          type: string
      - name: offset
        in: query
        description: |-
          Indicates start of record. Start of record by default is from 1.
          Use this in combination with limit for paginating results
        schema:
          type: integer
          format: int32
      - name: omitNullFields
        in: query
        description: |-
          Use this field to control the null value fields in the response
          set. It accepts 'true' or 'false'. The default is set to 'true'. true indcates
          that the response set will not contain the fields that have null value and
          false indicates the response will contain the fields that have the null
          values
        schema:
          type: string
      - name: limit
        in: query
        description: |-
          Indicates no of records to be returned. Default is 10.
          Use this in combination with offset for paginating results
        schema:
          type: integer
          format: int32
      - name: fields
        in: query
        description: |-
          Use this to determine the fields returned in the response. Separate the required fields with a comma.
          Ex: fields=fmno,skillType.
          If not passed, all the available fields will be returned
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPersonSkillsResponse'
        "404":
          description: Resource not found
        "500":
          description: Internal Server Error
      security:
      - oauth_clientcredentials: []

components:
  schemas:
    GetPersonSkillsResponse:
      description: Response Model
      type: object
      properties:
        response:
          $ref: '#/components/schemas/GetPersonSkillsPayload'

    GetPersonSkillsPayload:
      description: Returns person skills data.
      type: object
      properties:
        noOfRecords:
          description: Total Number of Records
          type: integer
          format: int64
        apiVersion:
          description: API version
          type: string
        params:
          $ref: '#/components/schemas/Parameters'
        person_skills:
          type: array
          items:
            $ref: '#/components/schemas/PersonSkill'

    Parameters:
      description: optional query parameters
      type: object
      properties:
        limit:
          description: Indicates no of records to be returned. Default is 10. Use this in combination with offset for paginating results
          type: integer
          format: int32
        offset:
          description: Indicates start of record. Start of record by default is from 1. Use this in combination with limit for paginating results
          type: integer
          format: int32

    PersonSkill:
      description: person skill data
      type: object
      properties:
        surveyQuestionType:
          description: Survey Question Type
          type: string
        updateDate:
          description: Update Date
          type: string
        skillType:
          description: Skill Type
          type: string
        source:
          description: source
          type: string
        skillCategory:
          description: skillCategory
          type: string
        proficiency:
          description: proficiency
          type: integer
          format: int32
        skillGroup:
          description: Skill Group
          type: string
        personSkillId:
          description: Person Skill Id
          type: integer
          format: int64
        skill:
          description: skill
          type: string
        fmno:
          description: fmno
          type: string
        createDate:
          description: createDate
          type: string

  securitySchemes:
    oauth_clientcredentials:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://dev-apioauth.mckinsey.com/asg/oauth2/access_token
          scopes: {}
          tokenUrl: https://dev-apioauth.mckinsey.com/asg/oauth2/access_token?grant_type=client_credentials