openapi: 3.0.3
info:
  title: "Person Locations History API"
  version: "1.0"
  description: This is the Person Locations History API

servers:
  - url: https://dev-api.mckinsey.com/

externalDocs:
  description: Find out more
  url: https://apidocs.intranet.mckinsey.com

tags:
  - name: PersonLocationsHistoryV1
    externalDocs:
      description: Find out more
      url: 'https://dev-apiportal.mckinsey.com/apis'

paths:
  /historical/v1/person_locations/history:
    get:
      tags:
        - PersonLocationsHistoryV1
      operationId: getPersonLocationsHistory
      summary: The API returns historic locations data
      description: |-
        <b>API Description :</b> This API provides provides all Office location a person has worked in the Firm
        and the period worked in each office along with rehire information ( if applicable)<br/>
        <b>Business Logic/Filter on data :</b> Data available for all FIRM members.<br/>
        <b>Sourced from:</b> NA<br/>
        <b>Source overview:</b> APIx>Solr>Firm Wide DataWarehouse<br/>
        <b>Works with ''Try it Out''?:</b> Yes<br/>
        <b>Application Context/User Context/Both:</b> Application Context<br/>
        <b>Caching and frequency :</b> No caching, database refresh frequency is every 2 hours starting 01:30 AM EST<br/>
        <b>Any exceptional scenarios associated to API?:</b> The api returns 10 records by default. If you wish to change
        this use the limit query parameter. Also an offset is provided and can be used in combination with limit
        for paginating results<br/>
        <b>Security Level:</b> Level 2 (Permissioned)<br/>
        <b>Hypermedia Links:</b> Yes<br/>
      parameters:
      - name: q
        in: query
        description: |-
          Use the "q" parameter to search for the locations.<br/>
          For locations for a specific person fmno use q=fmno:127642.<br/>
          For multiple fields, separate the fields by 'AND' keyword
            For Ex: q=fmno:127642 AND countryName:"United Kingdom"<br/>
          Date Range searches are also supported
            Ex: q=effectiveEndDate:[1989-12-22T00:00:00Z TO 1990-12-22T00:00:00Z]<br/>'
        required: true
        schema:
          type: string
      - name: historyType
        in: query
        description: |-
          value "all" will give complete history of a person based upon its location and value "firm"
          will give history of a firm member by location
        schema:
          type: string
      - name: personType
        in: query
        description: Status of a person by location
        schema:
          type: string
      - name: geoLocationCode4
        in: query
        description: Four letter code which identifies the Geo Location code to which Firm Member belongs to
        schema:
          type: string
      - name: offset
        in: query
        description: |-
          Indicates start of record. Start of record by default is from 1.
          Use this in combination with limit for paginating results
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        description: |-
          Indicates no of records to be returned. Default is 10.
          Use this in combination with offset for paginating results
        schema:
          type: integer
          format: int32
      - name: fields
        in: query
        description: |-
          Use this to determine the fields returned in the response. Separate the required fields with a comma.
          Ex: fmno,fdwPersonId.
          If not passed, all the available fields will be returned'
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPersonLocationsHistoryResponse'
        "404":
          description: Resource not found
        "500":
          description: Internal Server Error
      security:
      - oauth_clientcredentials: []

  /historical/v1/person_locations/countries/history:
    get:
      tags:
        - PersonLocationsHistoryV1
      operationId: getPersonLocationCountriesHistory
      summary: This API returns the Office location a person has worked in the Firm aggregated by country
      description: |-
        <b>API Description:</b> This API provides the Office location a person has worked in the Firm aggregated by country<br/>
        <b>Business Logic/Filter on data:</b> Data available for all FIRM members.<br/>
        <b>Sourced from:</b> NA<br/>
        <b>Source overview:</b> APIx>Solr>Firm Wide DataWarehouse<br/>
        <b>Works with "Try it Out"?:</b> Yes<br/>
        <b>Application Context/User Context/Both:</b> Application Context<br/>
        <b>Caching and frequency:</b> No caching, database refresh frequency is every 12 hours starting 9:00 AM EST<br/>
        <b>Any exceptional scenarios associated to API?:</b> The api returns 10 records by default. If you wish to change
        this use the limit query parameter. Also an offset is provided and can be used in combination with limit for paginating results<br/>
        <b>Security Level:</b> Level 2 (Permissioned)<br/>
        <b>Hypermedia Links:</b> Yes<br/>
      parameters:
      - description: Use the 'q' parameter to search for the locations.
        in: query
        name: q
        required: true
        schema:
          type: string
      - name: countryName
        in: query
        description: Look up by country name
        schema:
          type: string
      - name: offset
        in: query
        description: |-
          Indicates start of record. Start of record by default is from 1.
          Use this in combination with limit for paginating results
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        description: |-
          Indicates no of records to be returned. Default is 10.
          Use this in combination with offset for paginating results
        schema:
          type: integer
          format: int32
      - name: fields
        in: query
        description: |-
          Use this to determine the fields returned in the response. Separate the required fields with a comma.
          Ex: fmno,fdwPersonId
          If not passed, all the available fields will be returned'
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPersonLocationCountriesHistoryResponse'
        "404":
          description: Resource not found
        "500":
          description: Internal Server Error
      security:
      - oauth_clientcredentials: []

components:
  schemas:
    GetPersonLocationsHistoryResponse:
      type: object
      properties:
        response:
          $ref: '#/components/schemas/GetPersonLocationsHistoryPayload'

    GetPersonLocationsHistoryPayload:
      type: object
      properties:
        noOfRecords:
          description: Total Number of Records fetched
          type: integer
          format: int64
        apiVersion:
          description: API version
          type: string
        params:
          $ref: '#/components/schemas/Parameters'
        person_locations:
          type: array
          items:
            $ref: '#/components/schemas/PersonLocationHistory'

    PersonLocationHistory:
      type: object
      properties:
        id:
          description: Field that uniquely determines a record.(Not from datawarehouse)
          type: string
        fmno:
          description: Firm Member's/External workers firm member number. (Unique identifier for business use).
          type: string
        fdwPersonId:
          description: System generated  Identifier of a Person in FDW for every FMNO
          type: integer
          format: int64
        officeCode:
          description: Three letter code which identifies the Goc Office code to which Firm Member belongs to
          type: string
        officeDesc:
          description: description of the Goc Office
          type: string
        officeClusterCode:
          description: Two letter code to which a Goc office is rolled up
          type: string
        officeClusterDesc:
          description: ""
          type: string
        countryName:
          description: Country Name to which Geo Location Offices belongs to
          type: string
        creationDate:
          description: Country Name to which Geo Location Offices belongs to
          type: string
        region:
          description: Region name
          type: string
        rehireFlag:
          description: Flag indicating whether or not someone is a rehire
          type: string
        effectiveStartDate:
          description: The date on which a office value becomes available for use
          type: string
        effectiveEndDate:
          description: The date on which a location value becomes invalid and is no longer applicable
          type: string
        city:
          description: City Name
          type: string
        geoLocationCode4:
          description: Geo Location Code4
          type: string
        updateDate:
          description: Audit column which identifies the date when the marital status was last updated in the FDW
          type: string
        personType:
          description: Audit column which identifies the date when the marital status was last updated in the FDW
          type: string
        historyType:
          description: Audit column which identifies the date when the marital status was last updated in the FDW
          type: string

    GetPersonLocationCountriesHistoryResponse:
      type: object
      properties:
        response:
          $ref: '#/components/schemas/GetPersonLocationCountriesHistoryPayload'

    GetPersonLocationCountriesHistoryPayload:
      description: List of Person Functions
      type: object
      properties:
        noOfRecords:
          description: total Number of Records fetched.
          type: integer
          format: int64
        apiVersion:
          description: total Number of Records fetched.
          type: string
        params:
          $ref: '#/components/schemas/Parameters'
        person_location_countries:
          type: array
          items:
            $ref: '#/components/schemas/PersonLocationCountryHistory'

    PersonLocationCountryHistory:
      description: List of Person Locations aggregated by country
      type: object
      properties:
        fmno:
          description: Firm Member's/External workers firm member number. (Unique identifier for business use).
          type: string
        fdwPersonId:
          description: System generated  Identifier of a Person in FDW for every FMNO
          type: integer
          format: int64
        countryName:
          description: Country Name to which Geo Location Offices belongs to
          type: string
        rank:
          description: Rank
          type: integer
          format: int32
        totalFmnoHours:
          description: Total FMNO hours
          type: integer
          format: int32
        totalHoursPerCountry:
          description: Total hours in each country
          type: integer
          format: int32
        percent:
          description: Percentage
          type: number
          format: double
        creationDate:
          description: Country Name to which Geo Location Offices belongs to
          type: string


    Parameters:
      description: optional query parameters
      type: object
      properties:
        q:
          description: |-
            Use the "q" parameter to search for the functions.
            For functions for a specific person fmno use q=fmno:127642.
            For all records for a specific function use q=function:"Operations"
            You can also use a wildcard
              Ex: q=function:"Strategy%"
            For multiple fields separate the fields by 'AND' keywords.
            For Ex: q=fmno:127642 AND function:"Operations"
          type: string
        limit:
          description: |-
            Indicates no of records to be returned. Default is 10. Use this in combination with offset for paginating results
          type: integer
          format: int32
        offset:
          description: |-
            Indicates start of record. Start of record by default is from 1.
            Use this in combination with limit for paginating results
          type: integer
          format: int32
        fields:
          description: |-
            Use this to determine the fields returned in the response. Separate the required fields with a comma.
            Ex: fmno,fdwPersonId.
            If not passed, all the available fields will be returned
          type: string

  securitySchemes:
    oauth_clientcredentials:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://dev-apioauth.mckinsey.com/asg/oauth2/access_token
          scopes: {}
          tokenUrl: https://dev-apioauth.mckinsey.com/asg/oauth2/access_token?grant_type=client_credentials