openapi: 3.0.3
info:
  title: "Person Practice Affiliations API"
  version: "1.0"
  description: This is the Person Practice Affiliations API

servers:
  - url: https://dev-api.mckinsey.com/

externalDocs:
  description: Find out more
  url: https://apidocs.intranet.mckinsey.com

tags:
  - name: PersonPracticeAffiliationsV1
    externalDocs:
      description: Find out more
      url: 'https://dev-apiportal.mckinsey.com/apis'

paths:
  /human-resources/v1/person_practice_affiliations:
    get:
      tags:
        - PersonPracticeAffiliationsV1
      operationId: getPersonPracticeAffiliations
      summary: The API returns person practice affiliations
      description: |-
        <b>API Description :</b> This API provides practices that a Firm
        Member is affiliated with and the nature of the affiliation.<br/>
        <b>Business Logic/Filter on data :</b> For the specific set of fields, please use the fields
        parameter with an asterix or the specific field names. All of the fields in
        the response are indexed and can be used to filter results.<br/>
        <b>Source overview : </b> APIx>Solr>Datahub<br/>
        <b>Works with ''Try it Out''? :</b> Yes<br/>
        <b>Application Context/User Context/Both:</b> Application Context<br/>
        <b>Caching and frequency :</b> No caching, database refresh frequency is every 30 minutes<br/>
        <b>Any exceptional scenarios associated to API?:</b> None<br/>
        <b>Security Level:</b> Level 1 (Public)<br/>
        <b>Hypermedia Links:</b> No<br/>
        <b>Any exceptional scenarios associated to API?:</b> The api accepts
        the access token/apikey only in the header. The total no of records displayed
        are 10 with start record at 1. If you wish to change this, utilize the limit
        and the offset params.<br/>
      parameters:
      - name: q
        in: query
        description: Use the 'q' parameter to do a full text search on Person Practice Affiliations<br/>
        required: true
        schema:
          type: string
      - name: practiceAffiliationId
        in: query
        description: Unique identifier for the row
        schema:
          type: integer
          format: int64
      - name: practiceValue
        in: query
        description: The name of the practice affiliated to a Firm Member
        schema:
          type: string
      - name: fmno
        in: query
        description: Firm Member's/External workers firm member number. (Unique identifier
          for business use).
        schema:
          type: string
      - name: primary
        in: query
        description: Indicates whether the affiliation is primary or not.
        schema:
          type: string
      - name: comments
        in: query
        description: Additional information on the Firm Member's affiliation, typically
          provided by a manager or practice leader.
        schema:
          type: string
      - name: affiliationType
        in: query
        description: Indicates the nature of the affiliation between a Firm Member
          and a Practice (i.e. Core, Affiliated, or Interested).
        schema:
          type: string
      - name: practiceTagUrlId
        in: query
        description: Unique identifier for the practice.
        schema:
          type: string
      - name: startDate
        in: query
        description: Date on which the affiliation between the Firm Member and the
          Practice began.
        schema:
          type: string
      - name: endDate
        in: query
        description: The last day on which the Firm Member and Practice were affiliated.
        schema:
          type: string
      - name: createDate
        in: query
        description: Audit column which identifies the date when the record was created
          in the source system.
        schema:
          type: string
      - name: updateDate
        in: query
        description: Audit column which identifies the date when the record was last
          updated in the source system.
        schema:
          type: string
      - name: affiliationTypeImputed
        in: query
        description: affiliationTypeImputed.
        schema:
          type: string
      - name: lastUpdateDate
        in: query
        description: lastUpdateDate of the record.
        schema:
          type: string
      - name: offset
        in: query
        description: Indicates start of record. Start of record by default is from
          1. Use this in combination with limit for paginating results
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        description: Indicates no of records to be returned. Default is 10.Use this
          in combination with offset for paginating results
        schema:
          type: integer
          format: int32
      - name: fields
        in: query
        description: 'Use this to determine the fields returned in the response. Separate
          the required fields with a comma. Ex: fields=category, attribute, value.
          If not passed, all the available fields will be returned'
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
      - name: omitNullFields
        in: query
        description: Use this field to control the null value fields in the response
          set. It accepts 'true' or 'false'. The default is set to 'true'. true indicates
          that the response set will not contain the fields that have null value and
          false indicates the response will contain the fields that have the null
          values
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPersonPracticeAffiliationResponse'
        "404":
          description: Resource not found
        "500":
          description: Internal Server Error
      security:
      - oauth_clientcredentials: []

components:
  schemas:
    GetPersonPracticeAffiliationResponse:
      description: Response Model
      type: object
      properties:
        response:
          $ref: '#/components/schemas/Response'

    Response:
      description: Returns person practice affiliation
      type: object
      properties:
        noOfRecords:
          description: Total Number of Records
          type: integer
          format: int64
        apiVersion:
          description: API version
          type: string
        params:
          $ref: '#/components/schemas/Parameters'
        person_practice_affiliations:
          type: array
          items:
            $ref: '#/components/schemas/PersonPracticeAffiliation'

    Parameters:
      description: optional query parameters
      type: object
      properties:
        limit:
          description: Indicates no of records to be returned. Default is 10. Use
            this in combination with offset for paginating results
          type: integer
          format: int32
        offset:
          description: Indicates start of record. Start of record by default is from
            1. Use this in combination with limit for paginating results
          type: integer
          format: int32

    PersonPracticeAffiliation:
      description: person practice affiliations
      type: object
      properties:
        practiceAffiliationId:
          description: Related Sub BlockId
          type: integer
          format: int64
        practiceValue:
          description: The name of the practice affiliated to a Firm Member
          type: string
        updateDate:
          description: Update Date
          type: string
        comments:
          description: comments
          type: string
        endDate:
          description: End Date
          type: string
        affiliationType:
          description: Affiliation Type
          type: string
        fmno:
          description: fmno
          type: string
        practiceTagUrlId:
          description: practiceTagUrlId
          type: string
        startDate:
          description: Start Date
          type: string
        primary:
          description: primary
          type: string
        createDate:
          description: createDate
          type: string
        affiliationTypeImputed:
          description: affiliationTypeImputed
          type: string
        lastUpdateDate:
          description: Last Update Date
          type: string

  securitySchemes:
    oauth_clientcredentials:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://dev-apioauth.mckinsey.com/asg/oauth2/access_token
          scopes: {}
          tokenUrl: https://dev-apioauth.mckinsey.com/asg/oauth2/access_token?grant_type=client_credentials