openapi: 3.0.3
info:
  title: "Person Industry History API"
  version: "1.0"
  description: This is the Person Industry History API

servers:
  - url: https://dev-api.mckinsey.com/

externalDocs:
  description: Find out more
  url: https://apidocs.intranet.mckinsey.com

tags:
  - name: PersonIndustryHistoryV1
    externalDocs:
      url: 'https://dev-apiportal.mckinsey.com/apis'

paths:
  /historical/v1/person_industries/history:
    get:
      tags:
        - PersonIndustryHistoryV1
      operationId: getPersonIndustryHistory
      summary: The API returns person(s) historic indutries data
      description: |-
        <b>API Description:</b> This API provides all practice industries a person has worked in the last 3 years,
        rank based on hours spent and percentage<br/>
        <b>Business Logic/Filter on data:</b> Data available for FIRM(CSS and ESP) members only.<br/>
        <b>Source overview: </b> APIx>Solr>Firm Wide DataWarehouse<br/>
        <b>Hypermedia Links:</b>  No<br/>
        <b>Security Level:</b>  Level 2 (Permissioned)<br/>
        <b>Works with ''Try it Out''? :</b> Yes<br/>
        <b>Application Context/User Context/Both:</b> Application Context<br/>
        <b>Data refresh frequency:</b> Every 3 hours starting 02:45 AM EST<br/>
        <b>Caching and frequency:</b> None<br/>
        <b>Any exceptional scenarios associated to API?:</b> The api returns 10 records by default. If you wish to change
        this, use the limit query parameter. Also an offset is provided and can be used in combination with limit
        for paginating results.The api accepts the access token/apikey only in the header.<br/>
      parameters:
      - name: q
        in: query
        description: |-
          Use the ''q'' parameter to search for the industries.
          For industries for a specific person fmno use q=fmno:00257
          For all records for a specific industry use q=industry:"Public Sector"
          You can also use a wildcard
            Ex: q=industry:"Public%"
          For multiple fields separate the fields by "AND"
            Ex: q=fmno:00257 AND industry:"Public Sector"
        required: true
        schema:
          type: string
      - name: offset
        in: query
        description: Indicates start of record. Start of record by default is from 1. Use this in combination with limit for paginating results
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        description: Indicates no of records to be returned. Default is 10. Use this in combination with offset for paginating results
        schema:
          type: integer
          format: int32
      - name: fields
        in: query
        description: |-
          Use this to determine the fields returned in the response. Separate the required fields with a comma.
          Ex: fmno,fdwPersonId.
          If not passed, all the available fields will be returned
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
      - name: fmno
        in: query
        description: Firm Member's/External workers firm member number. (Unique identifier for business use).
        schema:
          type: string
      - name: fdwPersonId
        in: query
        description: System generated  Identifier of a Person in FDW for every FMNO
        schema:
          type: integer
          format: int64
      - name: industry
        in: query
        description: Industry Name
        schema:
          type: string
      - name: parentIndustry
        in: query
        description: Parent Industry Name
        schema:
          type: string
      - name: topParentIndustry
        in: query
        description: Top Parent Industry Name
        schema:
          type: string
      - name: creationDate
        in: query
        description: Date and time of creation
        schema:
          type: string
      - name: rank
        in: query
        description: Rank
        schema:
          type: integer
          format: int32
      - name: childRank
        in: query
        description: Child Rank
        schema:
          type: integer
          format: int32
      - name: totalHours
        in: query
        description: Total hours allocated to each FMNO
        schema:
          type: integer
          format: int32
      - name: totalIndustryHrs
        in: query
        description: Total hours utilised for one industry by FMNO
        schema:
          type: integer
          format: int32
      - name: totalParentIndustryHrs
        in: query
        description: Total hours utilised for parent industry by FMNO
        schema:
          type: integer
          format: int32
      - name: percent
        in: query
        description: Percentage of total hours used for industry
        schema:
          type: number
          format: float
      - name: omitNullFields
        in: query
        description: |-
          Use this field to control the null value fields in the response
          set. It accepts 'true' or 'false'. The default is set to 'true'. true indcates
          that the response set will not contain the fields that have null value and
          false indicates the response will contain the fields that have the null
          values
        schema:
          type: string
      - name: percentAtParentLvl
        in: query
        description: Percentage of total hours used for Parent industry
        schema:
          type: number
          format: float
      - name: updateDate
        in: query
        description: Audit column updateDate
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPersonIndustryHistoryResponse'
          description: Success
        "404":
          description: Resource not found
        "406":
          description: Input data is in invalid format
        "500":
          description: Internal Server Error
      security:
      - oauth_clientcredentials: []

components:
  schemas:
    GetPersonIndustryHistoryResponse:
      description: Response Model
      properties:
        response:
          $ref: '#/components/schemas/GetPersonIndustryHistoryPayload'
      type: object

    GetPersonIndustryHistoryPayload:
      description: List of Person Functions
      type: object
      properties:
        noOfRecords:
          description: total Number of Records fetched.
          type: integer
          format: int64
        apiVersion:
          description: API version
          type: string
        params:
          $ref: '#/components/schemas/Parameters'
        person_industries:
          type: array
          items:
            $ref: '#/components/schemas/PersonIndustryHistory'

    Parameters:
      type: object
      description: optional query parameters
      properties:
        limit:
          description: Indicates no of records to be returned. Default is 10. Use this in combination with offset for paginating results
          type: integer
          format: int32
        offset:
          description: Indicates start of record. Start of record by default is from 1. Use this in combination with limit for paginating results
          type: integer
          format: int32

    PersonIndustryHistory:
      type: object
      description: List of Person Industries
      properties:
        fmno:
          description: Firm Member's/External workers firm member number. (Unique identifier for business use).
          type: string
        fdwPersonId:
          description: System generated  Identifier of a Person in FDW for every FMNO
          type: integer
          format: int64
        industry:
          description: Industry Name
          type: string
        parentIndustry:
          description: Parent Industry Name
          type: string
        topParentIndustry:
          description: Top Parent Industry Name
          type: string
        creationDate:
          description: Date and time of creation
          type: string
        rank:
          description: Rank
          type: integer
          format: int32
        childRank:
          description: Child Rank
          type: integer
          format: int32
        totalHours:
          description: Total hours allocated to each FMNO
          type: integer
          format: int32
        totalIndustryHrs:
          description: Total hours utilised for one industry by FMNO
          type: integer
          format: int32
        totalParentIndustryHrs:
          description: Total hours utilised for parent industry by FMNO
          type: integer
          format: int32
        percent:
          description: Percentage of total hours used for industry.
          type: number
          format: float
        percentAtParentLvl:
          description: Percentage of total hours used for Parent industry.
          type: number
          format: float
        updateDate:
          description: Audit column updateDate
          type: string

  securitySchemes:
    oauth_clientcredentials:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://dev-apioauth.mckinsey.com/asg/oauth2/access_token
          scopes: {}
          tokenUrl: https://dev-apioauth.mckinsey.com/asg/oauth2/access_token?grant_type=client_credentials