openapi: 3.0.3
info:
  title: "Person Qualification Certs API"
  version: "1.0"
  description: This is the Person Qualification Certs API

servers:
  - url: https://dev-api.mckinsey.com/

externalDocs:
  description: Find out more
  url: https://apidocs.intranet.mckinsey.com

tags:
  - name: PersonQualificationCertsV1
    externalDocs:
      description: Find out more
      url: 'https://dev-apiportal.mckinsey.com/apis'

paths:
  /human-resources-restricted/v1/person_qualification_certs:
    get:
      tags:
        - PersonQualificationCertsV1
      operationId: getPersonQualificationCerts
      summary: The API returns person qualification certs
      description: |-
        <b>API Description:</b> This API provides Firm members’ qualifications including certificates and credentials.<br/>
        <b>Business Logic/Filter on data:</b> For the specific set of fields, please use the fields parameter with an asterix or the specific field names. All of the fields in the response are indexed and can be used to filter results<br/>
        <b>Source overview: </b> APIx>Solr>Datahub<br/>
        <b>Hypermedia Links:</b> No<br/>
        <b>Security Level:</b> Level 2 (Permissioned)<br/>
        <b>Works with "Try it Out"?:</b> Yes<br/>
        <b>Application Context/User Context/Both:</b> Application Context<br/>
        <b>Data refresh frequency :</b>Every 3 hours<br/>
        <b>Caching enabled and time to live:</b> None<br/>
        <b>Any exceptional scenarios associated to API?:</b> The api accepts the access token/apikey only in the header.
        The total no of records displayed are 10 with start record at 1. If you wish to change this, utilize the limit
        and the offset params.<br/>
      parameters:
      - name: q
        in: query
        description: Use the 'q' parameter to do a full text search on Person Qualification Certs.<br/>
        required: true
        schema:
          type: string
      - name: primaryConcentration
        in: query
        description: Name of the main qualification/credential
        schema:
          type: string
      - name: qualificationId
        in: query
        description: The unique identifer for the qualification/credential for the Firm member.
        schema:
          type: integer
          format: int64
      - name: additionalConcentration
        in: query
        description: Name of the any other qualification/credential.
        schema:
          type: string
      - name: institution
        in: query
        description: The institution or source where the Firm Member's qualification/credential.
        schema:
          type: string
      - name: qualificationType
        in: query
        description: The kind of qualification such as Certicate, Badge, Credential.
        schema:
          type: string
      - name: fmno
        in: query
        description: Firm Member's/External workers Firm member number. (Unique identifier for business use).
        schema:
          type: string
      - name: qualificationProgress
        in: query
        description: Provides Firm Members' education information.
        schema:
          type: string
      - name: qualificationStatus
        in: query
        description: Indicates the state of the qualification/credential such as Revoked, Issued.
        schema:
          type: string
      - name: qualificationStartDate
        in: query
        description: The date that a Firm member began the degree or certificate.
        schema:
          type: string
      - name: qualificationEndDate
        in: query
        description: The date that a Firm member completed the degree or certificate.
        schema:
          type: string
      - name: qualificationCategory
        in: query
        description: Describes Firm Member's qualitifcation cateogry such as Certication or Credential.
        schema:
          type: string
      - name: createDate
        in: query
        description: The date that the qualification was entered into the Data Hub.
        schema:
          type: string
      - name: updateDate
        in: query
        description: The date that the qualification was undated in the Data Hub.
        schema:
          type: string
      - name: badge
        in: query
        description: The date that the qualification was undated in the Data Hub.
        schema:
          type: string
      - name: infoText
        in: query
        description: The date that the qualification was undated in the Data Hub.
        schema:
          type: string
      - name: templateId
        in: query
        description: The date that the qualification was undated in the Data Hub.
        schema:
          type: string
      - name: surveyQuestionType
        in: query
        description: The date that the qualification was undated in the Data Hub.
        schema:
          type: string
      - name: offset
        in: query
        description: |-
          Indicates start of record. Start of record by default is from 1.
          Use this in combination with limit for paginating results
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        description: |-
          Indicates no of records to be returned. Default is 10.
          Use this in combination with offset for paginating results
        schema:
          type: integer
          format: int32
      - name: fields
        in: query
        description: |-
          Use this to determine the fields returned in the response. Separate the required fields with a comma.
          Ex: fields=fmno,institution.
          If not passed, all the available fields will be returned
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
      - name: omitNullFields
        in: query
        description: Use this field to control the null value fields in the response
          set. It accepts 'true' or 'false'. The default is set to 'true'. true indicates
          that the response set will not contain the fields that have null value and
          false indicates the response will contain the fields that have the null
          values
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPersonQualificationCertsResponse'
        "404":
          description: Resource not found
        "500":
          description: Internal Server Error
      security:
      - oauth_clientcredentials: []

components:
  schemas:
    GetPersonQualificationCertsResponse:
      description: Response Model
      type: object
      properties:
        response:
          $ref: '#/components/schemas/GetPersonQualificationCertsPayload'

    GetPersonQualificationCertsPayload:
      description: Returns person qualification certs data.
      type: object
      properties:
        noOfRecords:
          description: Total Number of Records
          type: integer
          format: int64
        apiVersion:
          description: API version
          type: string
        params:
          $ref: '#/components/schemas/Parameters'
        person_qualification_certs:
          type: array
          items:
            $ref: '#/components/schemas/PersonQualificationCert'

    Parameters:
      description: optional query parameters
      type: object
      properties:
        limit:
          description: Indicates no of records to be returned. Default is 10. Use this in combination with offset for paginating results
          type: integer
          format: int32
        offset:
          description: Indicates start of record. Start of record by default is from 1. Use this in combination with limit for paginating results
          type: integer
          format: int32

    PersonQualificationCert:
      description: Person Qualification Cert data
      type: object
      properties:
        primaryConcentration:
          description: Name of the main qualification/credential
          type: string
        updateDate:
          description: Update Date
          type: string
        qualificationId:
          description: qualificationId
          type: integer
          format: int64
        additionalConcentration:
          description: additionalConcentration
          type: string
        institution:
          description: institution
          type: string
        qualificationType:
          description: qualificationType
          type: string
        qualificationStartDate:
          description: qualificationStartDate
          type: string
        fmno:
          description: fmno
          type: string
        qualificationProgress:
          description: qualificationProgress
          type: string
        qualificationStatus:
          description: qualificationStatus
          type: string
        qualificationEndDate:
          description: qualificationEndDate
          type: string
        qualificationCategory:
          description: qualificationCategory
          type: string
        createDate:
          description: createDate
          type: string
        surveyQuestionType:
          description: surveyQuestionType
          type: string
        badge:
          description: badge
          type: string
        infoText:
          description: infoText
          type: string
        templateId:
          description: templateId
          type: string

  securitySchemes:
    oauth_clientcredentials:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://dev-apioauth.mckinsey.com/asg/oauth2/access_token
          scopes: {}
          tokenUrl: https://dev-apioauth.mckinsey.com/asg/oauth2/access_token?grant_type=client_credentials