openapi: 3.0.3
info:
  title: "Person Functions History API"
  version: "1.0"
  description: This is the Person Functions History API

servers:
- url: https://qa-api.mckinsey.com/

externalDocs:
  description: Find out more
  url: https://apidocs.intranet.mckinsey.com

tags:
  - name: PersonFunctionsHistoryV1

paths:
  /historical/v1/person_functions/history:
    get:
      tags:
        - PersonFunctionsHistoryV1
      operationId: getPersonFunctionsHistory
      summary: The API returns person(s) historic functions data
      description: |-
        <b>API Description :</b> This API provides all practice functions
        a person has worked in the last 3 years or entire tenure, rank based on hours spent and percentage<br/>
        <b>Business Logic/Filter on data :</b> Data available for FIRM(CSS and ESP) members only.<br/>
        <b>Source overview : </b> APIx>Solr>Firm Wide DataWarehouse<br/>
        <b>Hypermedia Links :</b>  No<br/>
        <b>Security Level:</b>  Level 2 (Permissioned)<br/>
        <b>Works with ''Try it Out''? :</b> Yes<br/>
        <b>Application Context/User Context/Both:</b> Application Context<br/>
        <b>Data refresh frequency:</b> Every 3 hours starting 02:45 AM EST, no caching<br/>
        <b>Any exceptional scenarios associated to API?:</b> The api returns 10 records by default. If
        you wish to change this use the limit query parameter. Also an offset is provided
        and can be used in combination with limit for paginating results. The api
        accepts the access token/apikey only in the header.<br/>
      parameters:
      - name: q
        in: query
        description: |-
          Use the ''q'' parameter to search for the functions.<br/>
          For functions for a specific person fmno use q=fmno:00257<br/>
          For all records for a specific function use q=function:"Operations" or you could also use
          a wildcard Ex: q=function:"Strategy%"<br/>
          For multiple fields separate the fields by AND. For Ex: q=fmno:00257 AND function:"Operations"<br/>
        required: true
        schema:
          type: string
      - name: offset
        in: query
        description: |-
          Indicates start of record. Start of record by default is from 1.
          Use this in combination with limit for paginating results
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        description: |-
          Indicates no of records to be returned. Default is 10.
          Use this in combination with offset for paginating results
        schema:
          type: integer
          format: int32
      - name: fields
        in: query
        description: 'Indicates which fields wants to be returned using names. Allowed values: fmno,fdwPersonId .. etc'
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
      - name: fmno
        in: query
        description: Firm Member's/External workers firm member number. (Unique identifier for business use).
        schema:
          type: string
      - name: fdwPersonId
        in: query
        description: System generated  Identifier of a Person in FDW for every FMNO
        schema:
          type: integer
          format: int64
      - name: function
        in: query
        description: Function Name
        schema:
          type: string
      - name: parentFunction
        in: query
        description: Parent Function Name
        schema:
          type: string
      - name: topParentFunction
        in: query
        description: Top Parent Function Name
        schema:
          type: string
      - name: creationDate
        in: query
        description: Date and time of creation
        schema:
          type: string
      - name: rank
        in: query
        description: Rank
        schema:
          type: integer
          format: int32
      - name: childRank
        in: query
        description: Child Rank
        schema:
          type: integer
          format: int32
      - name: totalHours
        in: query
        description: Total hours allocated to each FMNO
        schema:
          type: number
          format: float
      - name: totalFunctionalHrs
        in: query
        description: Total hours utilised for one function by FMNO
        schema:
          type: number
          format: float
      - name: totalParentFunctionalHrs
        in: query
        description: Total hours utilised for parent function by FMNO
        schema:
          type: number
          format: float
      - name: percent
        in: query
        description: Percentage of total hours used for function
        schema:
          type: number
          format: float
      - name: omitNullFields
        in: query
        description: |-
          Use this field to control the null value fields in the response
          set. It accepts 'true' or 'false'. The default is set to 'true'. true indcates
          that the response set will not contain the fields that have null value and
          false indicates the response will contain the fields that have the null
          values
        schema:
          type: string
      - name: percentAtParentLvl
        in: query
        description: Percentage of total hours used for Parent function
        schema:
          type: number
          format: float
      - name: updateDate
        in: query
        description: Audit column updateDate
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPersonFunctionsHistoryResponse'
        "404":
          description: Resource not found
        "406":
          description: Input data is in invalid format
        "500":
          description: Internal Server Error
      security:
      - oauth_clientcredentials: []

components:
  schemas:
    GetPersonFunctionsHistoryResponse:
      description: Response Model
      type: object
      properties:
        response:
          $ref: '#/components/schemas/Response'

    Response:
      description: List of Person Functions
      type: object
      properties:
        noOfRecords:
          description: total Number of Records fetched.
          type: integer
          format: int64
        apiVersion:
          description: total Number of Records fetched.
          type: string
        params:
          $ref: '#/components/schemas/Parameters'
        person_functions:
          type: array
          items:
            $ref: '#/components/schemas/PersonFunction'

    Parameters:
      description: optional query parameters
      type: object
      properties:
        limit:
          type: integer
          format: int32
          description: |-
            Indicates no of records to be returned. Default is 10.
            Use this in combination with offset for paginating results
        offset:
          type: integer
          format: int32
          description: |-
            Indicates start of record. Start of record by default is from 1.
            Use this in combination with limit for paginating results

    PersonFunction:
      type: object
      properties:
        fmno:
          description: Firm Member's/External workers firm member number. (Unique identifier for business use).
          type: string
        fdwPersonId:
          description: System generated  Identifier of a Person in FDW for every FMNO
          type: integer
          format: int64
        function:
          description: Function Name
          type: string
        rank:
          description: Rank
          type: integer
          format: int32
        totalHours:
          description: Total hours allocated to each FMNO
          type: number
          format: float
        totalFunctionalHrs:
          description: Total hours utilised for one function by FMNO
          type: number
          format: float
        percent:
          description: Percentage of total hours used for function.
          type: number
          format: float
        updateDate:
          description: Audit column which identifies the date when the marital status
            was last updated in the FDW
          type: string
        creationDate:
          description: Date and time of creation
          type: string
        percentAtParentLvl:
          description: Percentage of total hours used for Parent function.
          type: number
          format: float
        topParentFunction:
          description: Top Parent Function Name
          type: string
        childRank:
          type: integer
          format: int32
        parentFunction:
          type: string
        totalParentFunctionalHrs:
          type: number
          format: float

  securitySchemes:
    oauth_clientcredentials:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://qa-apioauth.mckinsey.com/asg/oauth2/access_token
          scopes: {}
          tokenUrl: https://qa-apioauth.mckinsey.com/asg/oauth2/access_token?grant_type=client_credentials