openapi: 3.0.3
info:
  title: "Project Tags API"
  version: "1.0"
  description: "This is the Project Tags API"
servers:
  - url: https://dev-api.mckinsey.com/
externalDocs:
  description: Find out more
  url: https://apidocs.intranet.mckinsey.com
tags:
  - name: ProjectTagsV1
    externalDocs:
      description: Find out more
      url: https://dev-apiportal.mckinsey.com
paths:
  /projects/v1/projects/tags:
    get:
      tags:
        - ProjectTagsV1
      operationId: getProjectTags
      summary: The API returns fx rates history
      description: |-
        '<b>API Description : </b>This API provides the practice, taxonomy and knowledge tags assigned to Client, Non-Client and Prospective engagements at the tag-engagement key-value pair level.<br/>
        <b>Business Logic/Filter on data : </b>None<br/>
        <b>Source overview : </b> APIx>Solr>Datahub<br/>
        <b>Hypermedia Links :</b>  No<br/>
        <b>Security Level :</b> Level 3 (Permissioned)<br/>
        <b>Works with ''Try it Out''? :</b> Yes<br/>
        <b>Application Context/User Context/Both : </b>Application Context<br/>
        <b>Data refresh frequency : </b>Every 3 hours starting 00:46 AM EST<br/>
        <b>Caching enabled and time to live :</b> NA<br/>
        <b>Any exceptional scenarios associated to API? : </b> The api accepts the access token/apikey
        only in the header. The total no of records displayed are 10 with start record
        at 1. If you wish to change this, utilize the limit and the offset params.<br/>'

      parameters:
        - name: q
          in: query
          description: Use the 'q' parameter to do a full text search on Project Tags<br/>
          required: true
          schema:
            type: string
        - name: projectTagId
          in: query
          description: Unique identifier for the row.
          schema:
            type: integer
            format: int32
        - name: tagValue
          in: query
          description: The text value of the taxonomy concept or practice tag
          schema:
            type: string
        - name: lastUpdateDate
          in: query
          description: The date on which the tag detail was last updated to the Data
            Hub.
          schema:
            type: string
        - name: tagSubType
          in: query
          description: Indicates the kind of tag; typically differentientiates between
            a main tag and non-main tags.
          schema:
            type: string
        - name: tagIdentifierType
          in: query
          description: Indicator if the reference data is current state (URI/PoolParty)
            or legacy data (ORS/P3FI)
          schema:
            type: string
        - name: tagContext
          in: query
          description: Indicates how the tag is being used; the circumstances under
            which the tag should interpreted
          schema:
            type: string
        - name: legacyTagId
          in: query
          description: Unique identifier for the legacy tag
          schema:
            type: integer
            format: int32
        - name: tagIdentifier
          in: query
          description: 'Unique identifier for the tag value '
          schema:
            type: integer
            format: int32
        - name: tagIdentifierExt
          in: query
          description: 'Full URI of the tag value '
          schema:
            type: string
        - name: tagType
          in: query
          description: Indicates the nature of tag; often indicates the branch of the
            hierarchy the tag belongs to (e.g. Function or Industry).
          schema:
            type: string
        - name: projectId
          in: query
          description: The unique system generated numeric identifer for the engagement.
          schema:
            type: integer
            format: int32
        - name: engagementId
          in: query
          description: Engagement ID.
          schema:
            type: integer
            format: int64
        - name: chargeCode
          in: query
          description: Engagement identifier. Client or non client engagement code.
            Client engagement codes are prefixed with an accounting client code and
            have a numberic sequence as the suffix. Eg. ABC000. Non client engagement
            code are generally prefix with three letters "ZW%","ZX%","ZY%" or "ZZ%"
            and have a numeric sequnce as the suffix. eg.. ZZY000 (Also know as project
            code and engagement code)
          schema:
            type: string
        - name: createDate
          in: query
          description: Date when the record was created in the source system
          schema:
            type: string
        - name: offset
          in: query
          description: Indicates start of record. Start of record by default is from
            1. Use this in combination with limit for paginating results
          schema:
            type: integer
            format: int32
            default: 1
        - name: limit
          in: query
          description: Indicates no of records to be returned. Default is 10.Use this
            in combination with offset for paginating results
          schema:
            type: integer
            format: int32
            default: 10
        - name: fields
          in: query
          description: |-
            Use this to determine the fields returned in the response. Separate the required fields with a comma.
            Ex: fields=tagValue,tagSubType,projectId.
            If not passed, all the available fields will be returned
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - name: omitNullFields
          in: query
          description: Use this field to control the null value fields in the response
            set. It accepts 'true' or 'false'. The default is set to 'true'. true indcates
            that the response set will not contain the fields that have null value and
            false indicates the response will contain the fields that have the null
            values
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProjectTagsResponse'
        404:
          description: Resource not found
          content: {}
        500:
          description: Internal Server Error
          content: {}
      security:
        - oauth_clientcredentials: []
components:
  schemas:
    GetProjectTagsResponse:
      type: object
      description: Response Model
      properties:
        response:
          $ref: '#/components/schemas/Response'
    Response:
      type: object
      description: Response object for Project Tags
      properties:
        noOfRecords:
          type: integer
          format: int64
          description: Total Number of Records
        apiVersion:
          type: string
          description: API version
        params:
          $ref: '#/components/schemas/Parameters'
        project_tags:
          type: array
          description: List of Project Tags
          items:
            $ref: '#/components/schemas/ProjectTag'
    Parameters:
      type: object
      description: optional query parameters
      properties:
        limit:
          type: integer
          format: int32
          description: Indicates no of records to be returned. Default is 10.Use this
            in combination with offset for paginating results
        offset:
          type: integer
          format: int32
          description: Indicates start of record. Start of record by default is from
            1. Use this in combination with limit for paginating results
    ProjectTag:
      type: object
      description: project tags
      properties:
        projectTagId:
          type: integer
          format: int32
          description: Unique identifier for the row
        tagValue:
          type: string
          description: The text value of the taxonomy concept or practice tag
        lastUpdateDate:
          type: string
          description: The date on which the tag detail was last updated to the Data
            Hub
        tagSubType:
          type: string
          description: Indicates the kind of tag; typically differentientiates between
            a main tag and non-main tags.
        tagIdentifierType:
          type: string
          description: Indicator if the reference data is current state (URI/PoolParty)
            or legacy data (ORS/P3FI).
        tagContext:
          type: string
          description: Indicates how the tag is being used; the circumstances under
            which the tag should interpreted.
        tagIdentifierExt:
          type: string
          description: Full URI of the tag.
        legacyTagId:
          type: integer
          format: int32
          description: Unique identifier for the row.
        tagIdentifier:
          type: integer
          format: int32
          description: The unique identifier for the tag value
        tagType:
          type: string
          description: Indicates the nature of tag; often indicates the branch of
            the hierarchy the tag belongs to (e.g. Function or Industry).
        projectId:
          type: integer
          format: int32
          description: The unique system generated numeric identifer for the engagement.
        engagementId:
          type: integer
          format: int64
          description: Engagement ID.
        chargeCode:
          type: string
          description: Charge Code
        createDate:
          type: string
          description: Create Date
  securitySchemes:
    oauth_clientcredentials:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://dev-apioauth.mckinsey.com/asg/oauth2/access_token
          tokenUrl: https://dev-apioauth.mckinsey.com/asg/oauth2/access_token?grant_type=client_credentials
          scopes: {}